#!/bin/sh

remaps &
unclutter --ignore-scrolling &
picom &
mpd &
pidof -s runit &&
        ! pidof -s pulseaudio >/dev/null 2>&1 &&
        setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
hsetroot -cover ~/.local/share/mache_2.jpg
sleep 1 && ~/.config/polybar/launch.sh &
exec dwm
